:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-spring-data-reactive-redis
:java_version: 17

This guide walks you through the process of creating a functional reactive application that uses Spring Data to interact with Redis using the non-blocking Lettuce driver.

== What You Will Build

You'll build a Spring application that uses https://projects.spring.io/spring-data-redis/[Spring Data Redis] and https://projectreactor.io/[Project Reactor] to interact with a Redis data store reactively, storing and retrieving `Coffee` objects without blocking. This application uses Reactor's `Publisher` implementations based upon the Reactive Streams specification, namely `Mono` (for a Publisher returning 0 or 1 value) and `Flux` (for a Publisher returning 0 to n values).

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/guide_introduction.adoc[]

== Setting up the Redis server

Before you can build a messaging application, you need to set up the server that will
handle receiving and sending messages.
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/docker_compose_support.adoc[]

If you choose to run the Redis server yourself instead of using Spring Boot Docker Compose support, you have a few options:
- https://redis.io/download[Download the server] and manually run it
- Install with Homebrew, if you use a Mac
- Manually run the `compose.yaml` file with `docker compose up`

If you go with any of these alternate approaches, you should remove the `spring-boot-docker-compose` dependency from the Maven or Gradle build file.
You will also need to add configuration to an `application.properties` file, as described in greater detail in the <<_preparing_to_build_the_application>> section.
As mentioned earlier, this guide assumes that you use Docker Compose support in Spring Boot, so additional changes to `application.properties` are not required at this point.

[[scratch]]
== Starting with Spring Initializr

You can use this https://start.spring.io/#!type=maven-project&language=java&packaging=jar&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=data-redis-reactive,lombok,webflux,docker-compose[pre-initialized project] and click Generate to download a ZIP file. This project is configured to fit the examples in this tutorial.

To manually initialize the project:

. Navigate to https://start.spring.io.
This service pulls in all the dependencies you need for an application and does most of the setup for you.
. Choose either Gradle or Maven and the language you want to use. This guide assumes that you chose Java.
. Click *Dependencies* and select *Spring Reactive Web*, *Spring Data Reactive Redis*, *Docker Compose Support* and *Lombok*.
. Click *Generate*.
. Download the resulting ZIP file, which is an archive of a web application that is configured with your choices.

NOTE: If your IDE has the Spring Initializr integration, you can complete this process from your IDE.

[[initial]]
== Create a Domain Class

Create a class representing a type of coffee we wish to stock in our coffee catalog:

`src/main/java/com/example/demo/Coffee.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/demo/Coffee.java[]
----

NOTE: I use Lombok in this example to eliminate the boilerplate code for constructors and so-called "data class" methods ( accessors/mutators, `equals()`, `toString()`, & `hashCode()`).


== Create a Configuration Class

Create a class that includes Spring Beans that support reactive Redis operations:

`src/main/java/com/example/demo/CoffeeConfiguration.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/demo/CoffeeConfiguration.java[]
----


== Create a Spring Bean to Load Data

Create a Spring Bean to load sample data for our application when we start it:

NOTE: Since we may (re)start our application multiple times, we should first remove any data that may still exist from previous executions. We do this with a `flushAll()` (Redis) server command. Once we've flushed any existing data, we create a small `Flux`, map each coffee name to a `Coffee` object, and save it to the reactive Redis repository. We then query the repo for all values and display them.

`src/main/java/com/example/demo/CoffeeLoader.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/demo/CoffeeLoader.java[]
----


== Create a RestController

Create a `RestController` to provide an external interface for our application:

`src/main/java/com/example/demo/CoffeeController.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/demo/CoffeeController.java[]
----


== Make the Application Executable

Although you can package this service as a traditional link:/understanding/WAR[WAR] file for deployment to an external application server, the simpler approach shown here creates a standalone application. You package everything in a single, executable JAR file, driven by a good old Java `main()` method. Along the way, you use Spring's support for embedding the link:/understanding/Netty[Netty] an asynchronous "container" as the HTTP runtime instead of deploying to an external instance.


`src/main/java/com/example/demo/DemoApplication.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/com/example/demo/DemoApplication.java[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/spring-boot-application.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_subhead.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_with_both.adoc[]


== Test the application

Now that the application is running, you can test it by accessing `http://localhost:8080/coffees` from HTTPie, curl, or your favorite browser.


== Summary

Congratulations! You have developed a Spring application that uses Spring Data and Redis for fully reactive, non-blocking database access!

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]
